fixtures:
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "0cd08b377b58927aefa15908689a69dfb99339d5"
  symlinks:
    "apt": "#{source_dir}"
