---
.travis.yml:
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" ORDERING="random"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" ORDERING="random"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" ORDERING="random"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes" ORDERING="random"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rspec-puppet
      version: '~> 2.1'
