name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
#      - name: Show
#        run: |
#          echo "TWINGATE_PUBLIC_REPO_KEY:"
#          echo "${{ secrets.TWINGATE_PUBLIC_REPO_KEY }}" | base64
    - name: "Install Twingate"
      uses: "twingate/github-action@v1"
      with:
        service-key: ${{ secrets.TWINGATE_PUBLIC_REPO_KEY }}
        debug: true
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    secrets: "inherit"
